# Generated by Django 2.2.3 on 2019-07-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('number_of_tickets', models.IntegerField()),
                ('price_of_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.Competition')),
            ],
        ),
    ]
