# Generated by Django 2.2.3 on 2019-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winning_ticket_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
