# Generated by Django 2.2.3 on 2019-07-19 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0002_winner_winning_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='win_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
