# Generated by Django 2.2.3 on 2019-08-14 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ticket_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None),
            preserve_default=False,
        ),
    ]
