# Generated by Django 2.2.3 on 2019-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
