# Generated by Django 2.2.3 on 2019-07-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20190718_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='is_published',
            new_name='is_active',
        ),
    ]
