# Generated by Django 2.2.3 on 2019-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20190719_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tickets_remaining',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
