# Generated by Django 2.2.3 on 2019-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
