# Generated by Django 2.2.3 on 2019-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20190725_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(default='2019-08-30'),
            preserve_default=False,
        ),
    ]
