# Generated by Django 2.2.3 on 2019-08-09 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_competition_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ticket_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 1], size=None),
            preserve_default=False,
        ),
    ]
