# Generated by Django 2.2.3 on 2019-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_competition_ticket_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='tickets_remaining',
            new_name='tickets_sold',
        ),
    ]
