# Generated by Django 2.2.3 on 2019-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20190810_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sale_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
